### PR TITLE
Fix/full undo redo

### LINKED ISSUE #3: ↩️ implement undo/redo for more actions
Currently, undo/redo only works on drawing things and moving widgets around, but not on creating/deleting widgets, editing graph widgets, etc.

This will be multiple commits.
- implement actions for addWidget, deleteWidget, converting widgets to/from graphs, etc.

### PR DESCRIPTION
**Pull request by henryholton**
> This is a big ole pr!

This PR implements history actions for all actions. This includes moving widgets, resizing widgets, adding expressions to graphs, removing expressions from graphs, changing graph colors, and worst of all, z-index management 😨

This makes it so that undo/redo functions for all actions and is totally comprehensive.
It also means I'm all caught up implementing actions for things so far, so now I don't have to play catch-up to get undo/redo working.

I believe there are still a few inconsistencies with z-index management, but they are few and far between, and undoing appears to always get you back to the initial state of the application.

Fixes #3

### CODE REVIEW

File: frontend/src/composables/useDraggables.ts [hunk 1]
```diff
@@ -122,14 +149,34 @@ export function useWidgetResize(id: string) {
...
+					new ActionGroup([
+						new ResizeWidgetAction(id, fromSize, toSize),
+						new ChangeZIndexAction(widget, newZIndex, startZIndex),
+					]),
+				)
+			} else if (resized) {
+				pushAction(new ResizeWidgetAction(id, fromSize, toSize))
+			} else if (zIndexChanged) {
+				pushAction(new ChangeZIndexAction(widget, newZIndex, startZIndex))
+			}
```
Comment (HenryHell0) [inline frontend/src/composables/useDraggables.ts]: Here, this should follow a similar structure as useWidgetDrag, instead of these icky nested if statements

**Review by henryholton — COMMENTED** [review]
test test where does this comment go?

**Review by henryholton — COMMENTED** [review]
okay that one didn't seem to work test test where does this one go?

**Review by henryholton — COMMENTED** [review]
LGTM!! :)

**Review by henryholton — COMMENTED** [review]
LGTM!!! <3 :))))
